---

- name: Run Updates on App Servers and wait 10 mins
  hosts: WINSERVER2022-APP1
  vars:
  ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    win_updates:
      category_names:
        - CriticalUpdates
        - DefinitionUpdates
        - SecurityUpdates
        - Updates
    reboot: yes
    reboot_timeout: 600