- name: Run Updates on App Servers and wait 10 mins
  hosts: WINSERVER2022-APP1
  gather_facts: no
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Install all available updates
      win_updates:
        category_names: ['CriticalUpdates', 'SecurityUpdates', 'Updates', 'DefinitionUpdates']
        state: installed
      register: update_result

    - name: Reboot if required after updates
      win_reboot:
        post_reboot_delay: 10
      when: update_result.reboot_required

    - name: Check for pending reboots
      win_reboot:
        check: yes
      register: reboot_status

    - name: Reboot if pending reboot exists
      win_reboot:
      when: reboot_status.reboot_required | default(false)