---
- name: Copy files and delete old files from source directory
  hosts: all
  become: true
  vars:
    source_directory: /opt/config/homeassistant/backups
    destination_directory: /mnt/backup
    ansible_host_key_checking: false
    days_to_keep: 30

  tasks:
    - name: Ensure destination directory exists
      file:
        path: "{{ destination_directory }}"
        state: directory
        mode: '0755'

    - name: Copy files from source to destination
      copy:
        src: "{{ source_directory }}/"
        dest: "{{ destination_directory }}/"
        remote_src: yes

    - name: Find files older than 30 days in the source directory
      find:
        paths: "{{ source_directory }}"
        age: "{{ days_to_keep }}d"
      register: old_files

    - name: Remove files older than 30 days from the source directory
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_files.files }}"
      when: old_files.matched > 0
