- name: Copy files from source to target
  hosts: kitchenpi.jocknet.se
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  gather_facts: no
  tasks:
    - name: Fetch file from source host
      fetch:
        src: /opt/config/homeassistant/backup/test
        dest: /tmp/test
        flat: yes

- name: Transfer files to target host
  hosts: containerpi1.jocknet.se
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  gather_facts: no
  tasks:
    - name: Synchronize files to target host
      synchronize:
        src: /tmp/test
        dest: /mnt/backup/homeassistant/test
        mode: pull