- hosts: kitchenpi
  vars:
    ansible_host_key_checking: false ##If you get an error about hosts not trusted
  tasks:
    - name: Transfer homeassistant backup to backup directory
      synchronize:
        src: /opt/config/homeassistant/backup
        dest: /mnt/arkiv2/backup/homeassistant
      delegate_to: kitchenpi