- name: Copy files from source to target using SCP
  hosts: kitchenpi.jocknet.se
  gather_facts: no
  tasks:
    - name: Copy file from source to target
      shell: |
        scp /opt/config/homeassistant/backup/test {{ majorgonzo }}@{{ hostvars['containerpi1.jocknet.se'].containerpi1.jocknet.se }}:/mnt/backup/homeassistant/test/
      delegate_to: source_host
      run_once: true