- name: Run Updates on Servers and wait 15 mins
  hosts: all
  gather_facts: no
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Install all available updates
      win_updates:
        category_names: ['CriticalUpdates', 'SecurityUpdates', 'Updates', 'DefinitionUpdates']
        state: installed
      register: update_result

    - name: Reboot if required after updates
      win_reboot:
        post_reboot_delay: 15
      when: update_result.reboot_required

    - name: writing log
      shell: echo host:{{inventory_hostname}} ,title:{{ item.value.title }} ,kb number:{{ item.value.kb }}
      loop: "{{ update_result.updates | dict2items }}"
      delegate_to: localhost