- name: Run Updates on Servers and wait 10 mins
  hosts: all
  gather_facts: no
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Install all available updates
      win_updates:
        category_names: ['CriticalUpdates', 'SecurityUpdates', 'Updates', 'DefinitionUpdates']
        state: installed
      register: update_result

    - name: Reboot if required after updates
      win_reboot:
        post_reboot_delay: 15
      when: update_result.reboot_required

    - name: Check for pending reboots using cmd
      win_shell: shutdown /q /f
      register: pending_reboot_status
      ignore_errors: true

    - name: Reboot if pending reboot exists
      win_reboot:
        reboot_timeout: 600  # Set a timeout for the reboot (in seconds)
      when: pending_reboot_status.rc != 0