---
- name: install windows update
  hosts: all
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: create log path directory
      win_file:
        path: C:\temp\win-updates
        state: directory
    - name: install all updates
      ansible.windows.win_updates:
        category_names: '*'
        log_path: C:\temp\win-updates\ansible_wu4.log
        state: installed        
        reboot: true
        server_selection: windows_update
