- name: Check for Windows Updates and report back
  hosts: all
  gather_facts: no
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:

    - name: Check for missing updates
      win_updates:
        state: searched
      register: update_results

    - name: report update results
      shell: echo host:{{inventory_hostname}} ,title:{{ item.value.title }} ,kb number:{{ item.value.kb }}
      loop: "{{ update_result.updates | dict2items }}"
      delegate_to: localhost