- name: Set PowerShell execution policy
  hosts: all
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Set PowerShell execution policy
      ansible.builtin.script: 
        cmd: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe Set-ExecutionPolicy RemoteSigned -Force
